<?xml version='1.0' encoding='UTF-8'?><!-- Published by XML-WS Runtime (https://github.com/eclipse-ee4j/metro-jax-ws). Runtime's version is Eclipse Metro/4.0.4.payara-p1 (FISH-10142-Metro-4.0.4-fa01c0b; 2025-07-11T17:44:37+0100) XMLWS-Impl/4.0.3 XMLWS-API/4.0.2 XMLB-Impl/4.0.5 XMLB-API/4.0.2 git-revision#fa01c0b. --><xs:schema xmlns:tns="http://ws/" xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0" targetNamespace="http://ws/">

<xs:element name="insertarEstudiante" type="tns:insertarEstudiante"/>

<xs:element name="insertarEstudianteResponse" type="tns:insertarEstudianteResponse"/>

<xs:element name="listarEstudiantes" type="tns:listarEstudiantes"/>

<xs:element name="listarEstudiantesResponse" type="tns:listarEstudiantesResponse"/>

<xs:complexType name="listarEstudiantes">
<xs:sequence/>
</xs:complexType>

<xs:complexType name="listarEstudiantesResponse">
<xs:sequence>
<xs:element name="return" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="insertarEstudiante">
<xs:sequence>
<xs:element name="nombre" type="xs:string" minOccurs="0"/>
<xs:element name="apellido" type="xs:string" minOccurs="0"/>
<xs:element name="cedula" type="xs:string" minOccurs="0"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="insertarEstudianteResponse">
<xs:sequence>
<xs:element name="return" type="xs:string" minOccurs="0"/>
</xs:sequence>
</xs:complexType>
</xs:schema>